diff -uNr book/Makefile book.new/Makefile
--- book/Makefile	2020-06-17 14:58:22.430567779 +0800
+++ book.new/Makefile	2020-06-17 16:13:58.927092133 +0800
@@ -40,6 +40,7 @@
       --stringparam chunk.quietly $(CHUNK_QUIET) \
       --stringparam rootid "$(ROOT_ID)"          \
       --stringparam base.dir $(BASEDIR)/         \
+      --stringparam l10n.gentext.default.language "zh_cn"         \
       stylesheets/lfs-chunked.xsl                \
       $(RENDERTMP)/lfs-html.xml
